Csharp-Cumulative-Assignment-1/Csharp-Cumulative-Assignment-1/Controllers/CoursesPageController.cs
using Microsoft.AspNetCore.Mvc;
using Csharp_Cumulative_Assignment_1.Models;

namespace Csharp_Cumulative_Assignment_1.Controllers
{
    public class CoursesPageController : Controller
    {

        // API is responsible for gathering the information from the Database and MVC is responsible for giving an HTTP response
        // as a web page that shows the information written in the View

        // In practice, both the CoursesAPI and CoursesPage controllers
        // should rely on a unified "Service", with an explicit interface

        private readonly CoursesAPIController _api;

        public CoursesPageController(CoursesAPIController api)
        {
            _api = api;
        }


        /// <summary>
        /// When we click on the Courses button in Navugation Bar, it returns the web page displaying all the teachers in the Database school
        /// </summary>
        /// <returns>
        /// List of all Courses in the Database school
        /// </returns>
        /// <example>
        /// GET : api/CoursesPage/List  ->  Gives the list of all Courses in the Database school
        /// </example>

        public IActionResult ListCourses()
        {
            List<Course> Courses = _api.ListCourses();
            return View(Courses);
        }



        /// <summary>
        /// When we Select one Course from the list, it returns the web page displaying the information of the SelectedCourse from the database school
        /// </summary>
        /// <returns>
        /// Information of the SelectedCourse from the database school
        /// </returns>
        /// <example>
        /// GET :api/CoursesPage/ShowCourses/{id}  ->  Gives the information of the SelectedCourse
        /// </example>
        /// 
        public IActionResult ShowCourses(int id)
        {
            Course SelectedCourse = _api.FindCourse(id);
            return View(SelectedCourse);
        }



        // GET : CoursesPage/NewCourse
        [HttpGet]
        public IActionResult NewCourse(int id)
        {
            return View();
        }



        // POST: CoursesPage/CreateCourse
        [HttpPost]
        public IActionResult CreateCourse(Course NewCourse)
        {
            int CourseId = _api.AddCourse(NewCourse);

            // redirects to "Show" action on "Course" cotroller with id parameter supplied
            return RedirectToAction("ShowCourses", new { id = CourseId });
        }






        // GET : CoursesPage/DeleteConfirmCourse/{id}
        [HttpGet]
        public IActionResult DeleteConfirmCourse(int id)
        {
            Course SelectedCourse = _api.FindCourse(id);
            return View(SelectedCourse);
        }








        // POST: CoursesPage/DeleteCourse/{id}
        [HttpPost]
        public IActionResult DeleteCourse(int id)
        {
            int CourseId = _api.DeleteCourse(id);
            // redirects to list action
            return RedirectToAction("ListCourses");
        }




        // GET : CoursesPage/EditCourse/{id}
        [HttpGet]
        public IActionResult EditCourse(int id)
        {
            Course SelectedCourse = _api.FindCourse(id);
            return View(SelectedCourse);
        }



        // POST: CoursesPage/Update/{id}
        [HttpPost]
        public IActionResult Update(int id, string CourseCode, DateTime CourseStartDate, DateTime CourseFinishDate, string CourseName, int TeacherId)
        {
            Course UpdatedCourse = new Course();
            UpdatedCourse.CourseCode = CourseCode;
            UpdatedCourse.CourseStartDate = CourseStartDate;
            UpdatedCourse.CourseFinishDate = CourseFinishDate;
            UpdatedCourse.CourseName = CourseName;
            UpdatedCourse.TeacherId = TeacherId;


            // not doing anything with the response
            _api.UpdateCourse(id, UpdatedCourse);

            // redirects to show teacher
            return RedirectToAction("ShowCourses", new { id });
        }


    }
}

Csharp-Cumulative-Assignment-1/Csharp-Cumulative-Assignment-1/Controllers/StudentPageController.cs
using Microsoft.AspNetCore.Mvc;
using Csharp_Cumulative_Assignment_1.Models;

namespace Csharp_Cumulative_Assignment_1.Controllers
{
    public class StudentPageController : Controller
    {

        // API is responsible for gathering the information from the Database and MVC is responsible for giving an HTTP response
        // as a web page that shows the information written in the View

        // In practice, both the StudentAPI and StudentPage controllers
        // should rely on a unified "Service", with an explicit interface

        private readonly StudentAPIController _api;

        public StudentPageController(StudentAPIController api)
        {
            _api = api;
        }


        /// <summary>
        /// When we click on the Students button in Navugation Bar, it returns the web page displaying all the teachers in the Database student
        /// </summary>
        /// <returns>
        /// List of all Students in the Database student
        /// </returns>
        /// <example>
        /// GET : api/StudentPage/List  ->  Gives the list of all Students in the Database student
        /// </example>

        public IActionResult ListStudent()
        {
            List<Student> Students = _api.ListStudents();
            return View(Students);
        }



        /// <summary>
        /// When we Select one Student from the list, it returns the web page displaying the information of the SelectedStudent from the database student
        /// </summary>
        /// <returns>
        /// Information of the SelectedStudent from the database student
        /// </returns>
        /// <example>
        /// GET :api/StudentPage/Show/{id}  ->  Gives the information of the SelectedStudent
        /// </example>
        /// 
        public IActionResult ShowStudent(int id)
        {
            Student SelectedStudent = _api.FindStudent(id);
            return View(SelectedStudent);
        }



        // GET : StudentPage/NewStudent
        [HttpGet]
        public IActionResult NewStudent(int id)
        {
            return View();
        }



        // POST: StudentPage/CreateStudent
        [HttpPost]
        public IActionResult CreateStudent(Student NewStudent)
        {
            int StudentId = _api.AddStudent(NewStudent);

            // redirects to "Show" action on "Student" cotroller with id parameter supplied
            return RedirectToAction("ShowStudent", new { id = StudentId });
        }




        // GET : StudentPage/DeleteConfirmStudent/{id}
        [HttpGet]
        public IActionResult DeleteConfirmStudent(int id)
        {
            Student SelectedStudent = _api.FindStudent(id);
            return View(SelectedStudent);
        }





        // POST: StudentPage/DeleteStudent/{id}
        [HttpPost]
        public IActionResult DeleteStudent(int id)
        {
            int StudentId = _api.DeleteStudent(id);
            // redirects to list action
            return RedirectToAction("ListStudent");
        }



        // GET : StudentPage/EditStudent/{id}
        [HttpGet]
        public IActionResult EditStudent(int id)
        {
            Student SelectedStudent = _api.FindStudent(id);
            return View(SelectedStudent);
        }



        // POST: StudentPage/Update/{id}
        [HttpPost]
        public IActionResult Update(int id, string StudentFName, string StudentLName, string StudentNumber, DateTime StudentEnrolmentDate)
        {
            Student UpdatedStudent = new Student();
            UpdatedStudent.StudentFName = StudentFName;
            UpdatedStudent.StudentLName = StudentLName;
            UpdatedStudent.StudentNumber = StudentNumber;
            UpdatedStudent.StudentEnrolmentDate = StudentEnrolmentDate;


            // not doing anything with the response
            _api.UpdateStudent(id, UpdatedStudent);

            // redirects to show teacher
            return RedirectToAction("ShowStudent", new { id });
        }


    }
}

Csharp-Cumulative-Assignment-1/Csharp-Cumulative-Assignment-1/Controllers/TeacherPageController.cs
using Microsoft.AspNetCore.Mvc;
using Csharp_Cumulative_Assignment_1.Models;

namespace Csharp_Cumulative_Assignment_1.Controllers
{
    public class TeacherPageController : Controller
    {

        // API is responsible for gathering the information from the Database and MVC is responsible for giving an HTTP response
        // as a web page that shows the information written in the View

        // In practice, both the TeacherAPI and TeacherPage controllers
        // should rely on a unified "Service", with an explicit interface

        private readonly TeacherAPIController _api;

        public TeacherPageController(TeacherAPIController api)
        {
            _api = api;
        }


        /// <summary>
        /// When we click on the Teachers button in Navugation Bar, it returns the web page displaying all the teachers in the Database school
        /// </summary>
        /// <returns>
        /// List of all Teachers in the Database school
        /// </returns>
        /// <example>
        /// GET : api/TeacherPage/List  ->  Gives the list of all Teachers in the Database school
        /// </example>
        
        public IActionResult List()
        {
            List<Teacher> Teachers = _api.ListTeachers();
            return View(Teachers);
        }



        /// <summary>
        /// When we Select one Teacher from the list, it returns the web page displaying the information of the SelectedTeacher from the database school
        /// </summary>
        /// <returns>
        /// Information of the SelectedTeacher from the database school
        /// </returns>
        /// <example>
        /// GET :api/TeacherPage/Show/{id}  ->  Gives the information of the SelectedTeacher
        /// </example>
        /// 
        public IActionResult Show(int id)
        {
            Teacher SelectedTeacher = _api.FindTeacher(id);
            return View(SelectedTeacher);
        }




        // GET : TeacherPage/New
        [HttpGet]
        public IActionResult New(int id)
        {
            return View();
        }



        // POST: TeacherPage/Create
        [HttpPost]
        public IActionResult Create(Teacher NewTeacher)
        {
            int TeacherId = _api.AddTeacher(NewTeacher);

            // redirects to "Show" action on "Teacher" cotroller with id parameter supplied
            return RedirectToAction("Show", new { id = TeacherId });
        }






        // GET : TeacherPage/DeleteConfirm/{id}
        [HttpGet]
        public IActionResult DeleteConfirm(int id)
        {
            Teacher SelectedTeacher = _api.FindTeacher(id);
            return View(SelectedTeacher);
        }








        // POST: TeacherPage/Delete/{id}
        [HttpPost]
        public IActionResult Delete(int id)
        {
            int TeacherId = _api.DeleteTeacher(id);
            // redirects to list action
            return RedirectToAction("List");
        }



        // GET : TeacherPage/Edit/{id}
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Teacher SelectedTeacher = _api.FindTeacher(id);
            return View(SelectedTeacher);
        }



        // POST: TeacherPage/Update/{id}
        [HttpPost]
        public IActionResult Update(int id, string TeacherFName, string TeacherLName, decimal TeacherSalary, string EmployeeNumber, DateTime TeacherHireDate)
        {
            Teacher UpdatedTeacher = new Teacher();
            UpdatedTeacher.TeacherFName = TeacherFName;
            UpdatedTeacher.TeacherLName = TeacherLName;
            UpdatedTeacher.TeacherSalary = TeacherSalary;
            UpdatedTeacher.EmployeeNumber = EmployeeNumber;
            UpdatedTeacher.TeacherHireDate = TeacherHireDate;


            // not doing anything with the response
            _api.UpdateTeacher(id, UpdatedTeacher);


            // redirects to show teacher
            return RedirectToAction("Show", new { id });
        }


    }
}

Csharp-Cumulative-Assignment-1/Csharp-Cumulative-Assignment-1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Csharp_Cumulative_Assignment_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Csharp_Cumulative_Assignment_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Csharp_Cumulative_Assignment_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Swagger" asp-action="Index">API</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeacherPage" asp-action="List">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CoursesPage" asp-action="ListCourses">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentPage" asp-action="ListStudent">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Csharp_Cumulative_Assignment_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>